// Code generated by goctl. DO NOT EDIT.
package types

type WorkSpaceBase struct {
	Id            string   `json:"id,optional"`
	WorkSpaceName string   `json:"workSpaceName"`
	WorkSpaceDesc string   `json:"workSpaceDesc,optional"`
	WorkSpaceType string   `json:"workSpaceType"`
	WorkSpaceTag  []string `json:"workSpaceTag,optional"`
	WorkSpaceIcon string   `json:"workSpaceIcon,optional"`
}

type WorkSpaceNewRequest struct {
	WorkSpaceBase
}

type WorkSpaceNewResponse struct {
	WorkSpaceBase
	WorkSpaceConfig string `json:"workSpaceConfig"`
}

type WorkSpaceEditRequest struct {
	WorkSpaceBase
	WorkSpaceConfig string `json:"workSpaceConfig,optional"`
}

type WorkSpaceEditResponse struct {
	WorkSpaceBase
	WorkSpaceConfig string `json:"workSpaceConfig"`
}

type WorkRemoveRequest struct {
	Id string `json:"id,optional"`
}

type WorkSpaceRemoveResponse struct {
}

type WorkSpaceListRequest struct {
	WorkSpaceName string  `json:"workSpaceName,optional"`
	WorkSpaceType string  `json:"workSpaceType,optional"`
	WorkSpaceTag  []int64 `json:"workSpaceTag,optional"`
	Current       int     `json:"current"`
	PageSize      int     `json:"pageSize"`
}

type WorkSpaceListResponse struct {
	Current  int             `json:"current"`
	PageSize int             `json:"pageSize"`
	Total    int64           `json:"total"`
	Data     []WorkSpacePage `json:"data"`
}

type WorkSpacePage struct {
	WorkSpaceBase
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type WorkSpaceEditTagRequest struct {
	Id           string   `json:"id"`
	WorkSpaceTag []string `json:"workSpaceTag"`
}

type WorkSpaceEditTagResponse struct {
}

type TagListRequest struct {
	Name string `json:"name,optional"`
}

type TagListResponse struct {
	Tag []TagEntity `json:"tagList"`
}

type TagEntity struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

type TagEditRequest struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type TagEditResponse struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type TagRemoveRequest struct {
	Id int64 `json:"id"`
}

type TagRemoveResponse struct {
	Id int64 `json:"id"`
}

type MockRequest struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type MockInfo struct {
	Address   string   `json:"address"`
	PhoneNums []string `json:"phoneNums"`
}

type MockResponse struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type WorkSpaceCopyRequest struct {
	Id   string `json:"id"`
	Name string `json:"name,optional"`
}

type WorkSpaceCopyResponse struct {
	WorkSpaceBase
	WorkSpaceConfig string `json:"workSpaceConfig"`
}

type WorkSpaceEnvListRequest struct {
	Id string `json:"id"`
}

type WorkSpaceEnvListResponse struct {
	EnvList []EnvList `json:"envList"`
}

type EnvList struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type WorkSpaceEnvEditRequest struct {
	Id  string    `json:"id"`
	Env []EnvList `json:"env"`
}

type WorkSpaceEnvEditResponse struct {
}

type WorkSpaceExportRequest struct {
	Id string `json:"id"`
}

type WorkSpaceExportResponse struct {
	Export string `json:"export"`
}

type WorkSpaceImportRequest struct {
	WorkSpaceBase
	Export string `json:"export"`
}

type WorkSpaceImportResponse struct {
	WorkSpaceBase
}

type CanvasRunRequest struct {
	Id string `json:"id" desc:"空间ID"`
}

type CanvasRunResponse struct {
	Ts       int64             `json:"ts"`
	Id       string            `json:"id"`
	MetaData map[string]string `json:"metadata"`
	Data     interface{}       `json:"data"`
}

type CanvasRunSingleRequest struct {
	Id     string `json:"id" desc:"空间ID"`
	NodeId string `json:"nodeId" desc:"节点ID"`
}

type CanvasRunSingleResponse struct {
	Ts       int64             `json:"ts"`
	Id       string            `json:"id"`
	MetaData map[string]string `json:"metadata"`
	Data     interface{}       `json:"data"`
}

type CanvasRunSingleDetailRequest struct {
	Id     string `json:"id"`     // 空间ID
	NodeId string `json:"nodeId"` // 节点ID
}

type CanvasRunSingleDetailResponse struct {
	NodeId    string `json:"nodeId"`
	NodeName  string `json:"nodeName"`
	StartTime int64  `json:"startTime"`
	Duration  int64  `json:"duration"`
	Status    string `json:"status"`
	Error     string `json:"error"`
	Input     string `json:"input"`
	Output    string `json:"output"`
}

type GetCanvasRunHistoryReq struct {
	WorkSpaceId string `path:"workSpaceId"`
}

type RunHistoryRecord struct {
	Id             string `json:"id"`             // 运行记录ID
	StartTime      string `json:"startTime"`      // 开始时间，ISO格式
	Duration       int64  `json:"duration"`       // 总耗时(ms)
	Status         string `json:"status"`         // 运行状态
	ComponentCount int64  `json:"componentCount"` // 组件数量
}

type GetCanvasRunHistoryResp struct {
	Records []RunHistoryRecord `json:"records"`
	Total   int64              `json:"total"` // 总记录数
}

type GetCanvasRunDetailReq struct {
	RecordId string `path:"recordId"` // 运行记录ID
}

type GetCanvasRunDetailResp struct {
	Id         string            `json:"id"`         // 运行记录ID
	StartTime  string            `json:"startTime"`  // 开始时间
	Duration   int64             `json:"duration"`   // 总耗时(ms)
	Status     string            `json:"status"`     // 运行状态 success/failed
	Error      string            `json:"error"`      // 错误信息
	Components []ComponentDetail `json:"components"` // 组件列表
}

type ComponentDetail struct {
	Id        string                 `json:"id"`        // 组件ID
	Name      string                 `json:"name"`      // 组件名称
	Logic     string                 `json:"logic"`     // 组件类型
	StartTime int64                  `json:"startTime"` // 开始时间戳
	Duration  int64                  `json:"duration"`  // 耗时(ms)
	Status    string                 `json:"status"`    // 组件运行状态 success/failed
	Error     string                 `json:"error"`     // 组件错误信息
	Input     map[string]interface{} `json:"input"`     // 输入参数
	Output    map[string]interface{} `json:"output"`    // 输出结果
}

type CanvasDraftRequest struct {
	Id    string                 `json:"id"`
	Graph map[string]interface{} `json:"graph"`
}

type CanvasDraftResponse struct {
	Hash       string `json:"hash"`
	UpdateTime int64  `json:"updateTime"`
}

type EdgeCustomData struct {
	SourcePoint int `json:"sourcePoint"`
	TargetPoint int `json:"targetPoint"`
}

type CanvasDetailRequest struct {
	Id string `json:"id"`
}

type CanvasDetailResponse struct {
	Id    string                 `json:"id"`
	Name  string                 `json:"name"`
	Graph map[string]interface{} `json:"graph"`
}

type SaveCanvasHistoryReq struct {
	WorkspaceId string `json:"workspaceId"`
	Name        string `json:"name"`
}

type SaveCanvasHistoryResp struct {
	Id int64 `json:"id"`
}

type GetCanvasHistoryListReq struct {
	Name        string `json:"name,optional"`
	Mode        int64  `json:"mode,optional" common:"0-草稿 1-api 2-job"`
	WorkspaceId string `json:"workspaceId"`
	Current     int    `json:"current"`
	PageSize    int    `json:"pageSize"`
}

type GetCanvasHistoryListResp struct {
	Records []CanvasHistoryRecord `json:"records"`
	Total   int64                 `json:"total"` // 总记录数
}

type CanvasHistoryRecord struct {
	Id         int64  `json:"id"`
	CreateTime string `json:"createTime"`
	Mode       int64  `json:"mode" common:"0-草稿 1-api 2-job"`
	Name       string `json:"name"`
}

type GetCanvasHistoryDetailReq struct {
	Id int64 `json:"id"`
}

type GetCanvasHistoryDetailResp struct {
	Id    int64                  `json:"id"`
	Name  string                 `json:"name"`
	Graph map[string]interface{} `json:"graph"`
}

type RestoreCanvasHistoryReq struct {
	Id int64 `json:"id"`
}

type RestoreCanvasHistoryResp struct {
	Id          int64  `json:"id"`
	WorkspaceId string `json:"workspaceId"`
}

type ApiPublishRequest struct {
	Id      string `json:"id" desc:"空间ID"`
	ApiName string `json:"apiName" desc:"名称"`
	ApiDesc string `json:"apiDesc" desc:"描述"`
}

type ApiPublishResponse struct {
	ApiId string `json:"apiId"`
}

type ApiPublishListRequest struct {
	Current  int    `json:"current"`
	PageSize int    `json:"pageSize"`
	Id       string `json:"id,optional" desc:"API_ID 非必填"`
	Name     string `json:"name,optional"`
}

type ApiPublishListResponse struct {
	Current  int              `json:"current"`
	PageSize int              `json:"pageSize"`
	Total    int64            `json:"total"`
	List     []ApiPublishList `json:"list"`
}

type ApiPublishList struct {
	WorkSpaceId string `json:"workSpaceId"`
	ApiId       string `json:"apiId"`
	ApiName     string `json:"apiName"`
	ApiDesc     string `json:"apiDesc"`
	PublishTime string `json:"publishTime"`
	Status      string `json:"status" desc:"上下线状态ON OFF"`
}

type ApiOnOffRequest struct {
	ApiId  string `json:"apiId"`
	Status string `json:"status" desc:"上下线状态ON OFF"`
}

type ApiOnOffResponse struct {
	ApiId  string `json:"apiId"`
	Status string `json:"status" desc:"上下线状态ON OFF"`
}

type ApiRecordsRequest struct {
	Current   int    `json:"current"`
	PageSize  int    `json:"pageSize"`
	ApiId     string `json:"apiId,optional" desc:"apiId"`
	StartTime int64  `json:"startTime,optional" desc:"开始时间"`
	EndTime   int64  `json:"endTime,optional" desc:"结束时间"`
	Request   string `json:"request,optional" desc:"请求参数"`
	Response  string `json:"response,optional" desc:"响应参数"`
}

type ApiRecordsResponse struct {
	Current  int          `json:"current"`
	PageSize int          `json:"pageSize"`
	Total    int64        `json:"total"`
	List     []ApiRecords `json:"list"`
}

type ApiRecords struct {
	ApiId    string `json:"apiId"`
	ApiName  string `json:"apiName" desc:"名称"`
	CallTime string `json:"callTime"`
	Status   string `json:"status"`
	TraceId  string `json:"traceId"`
	Param    string `json:"param"`
	Extend   string `json:"extend"`
}

type ApiSecretKeyListRequest struct {
	ApiId    string `json:"apiId"`
	Current  int    `json:"current"`
	PageSize int    `json:"pageSize"`
}

type ApiSecretKeyListResponse struct {
	Current  int            `json:"current"`
	PageSize int            `json:"pageSize"`
	Total    int64          `json:"total"`
	List     []ApiSecretKey `json:"list"`
}

type ApiSecretKey struct {
	ApiId          string `json:"apiId"`
	Name           string `json:"name"`
	SecretKey      string `json:"secretKey"`
	ExpirationTime string `json:"expirationTime"`
	Status         string `json:"status" desc:"状态 ON OFF"`
}

type ApiSecretKeyCreateRequest struct {
	ApiId          string `json:"apiId"`
	Name           string `json:"name"`
	SecretKey      string `json:"secretKey,optional"`
	ExpirationTime int64  `json:"expirationTime"`
}

type ApiSecretKeyCreateResponse struct {
	ApiId          string `json:"apiId"`
	Name           string `json:"name"`
	SecretKey      string `json:"secretKey"`
	ExpirationTime string `json:"expirationTime"`
}

type ApiSecretKeyUpdateStatusRequest struct {
	SecretKey string `json:"secretKey"`
	Status    string `json:"status" desc:"状态 ON OFF"`
}

type ApiSecretKeyUpdateStatusResponse struct {
	SecretKey string `json:"secretKey"`
	Status    string `json:"status" desc:"状态 ON OFF"`
}

type ApiSecretKeyUpdateExpirationTimeRequest struct {
	SecretKey      string `json:"secretKey"`
	ExpirationTime int64  `json:"expirationTime"`
}

type ApiSecretKeyUpdateExpirationTimeResponse struct {
	SecretKey      string `json:"secretKey"`
	ExpirationTime string `json:"expirationTime"`
}

type ApiSecretKeyDeleteRequest struct {
	SecretKey string `json:"secretKey"`
}

type ApiSecretKeyDeleteResponse struct {
	SecretKey string `json:"secretKey"`
}

type ApiHistoryRequest struct {
	WorkspaceId string `json:"workspaceId"`
	Current     int    `json:"current"`
	PageSize    int    `json:"pageSize"`
}

type ApiHistoryResponse struct {
	Current  int          `json:"current"`
	PageSize int          `json:"pageSize"`
	Total    int64        `json:"total"`
	List     []ApiHistory `json:"list"`
}

type ApiHistory struct {
	Id          int64  `json:"id"`
	WorkspaceId string `json:"workspaceId"`
	Name        string `json:"name"`
	CreateTime  string `json:"createTime"`
}

type ApiEditRequest struct {
	ApiId   string `json:"apiId"`
	ApiName string `json:"apiName"`
	ApiDesc string `json:"apiDesc"`
}

type ApiEditResponse struct {
	ApiId string `json:"apiId"`
}

type ApiCallRequest struct {
	ApiId  string `json:"apiId"`
	Url    string `json:"url"`
	Header string `json:"header"`
	Body   string `json:"body"`
}

type ApiCallResponse struct {
	Response string `json:"response"`
}

type ApiCallTemplateRequest struct {
	ApiId string `json:"apiId"`
}

type ApiCallTemplateResponse struct {
	ApiId  string `json:"apiId"`
	Url    string `json:"url"`
	Header string `json:"header"`
	Body   string `json:"body"`
}

type ApiExportCurlRequest struct {
	ApiId  string `json:"apiId"`
	Url    string `json:"url"`
	Header string `json:"header"`
	Body   string `json:"body"`
}

type ApiExportCurlResponse struct {
	Curl string `json:"curl"`
}

type ModuleListRequest struct {
}

type ModuleListResponse struct {
	Total   int          `json:"total"`
	Modules []ModuleData `json:"modules"`
}

type ModuleData struct {
	Index        int    `json:"index"`
	ModuleId     string `json:"moduleId"`
	ModuleName   string `json:"moduleName"`
	ModuleType   string `json:"moduleType"`
	ModuleConfig string `json:"moduleConfig"`
}

type ModuleNewRequest struct {
	Index        int    `json:"index"`
	ModuleName   string `json:"moduleName"`
	ModuleType   string `json:"moduleType"`
	ModuleConfig string `json:"moduleConfig"`
}

type ModuleNewResponse struct {
	ModuleId string `json:"moduleId"`
}

type ModuleEditRequest struct {
	Index        int    `json:"index"`
	ModuleId     string `json:"moduleId"`
	ModuleName   string `json:"moduleName"`
	ModuleType   string `json:"moduleType"`
	ModuleConfig string `json:"moduleConfig"`
}

type ModuleEditResponse struct {
	ModuleId string `json:"moduleId"`
}

type DatasourceListRequest struct {
	Current  int    `json:"current"`
	PageSize int    `json:"pageSize"`
	Type     string `json:"type,optional"`
	Name     string `json:"name,optional"`
	Status   string `json:"status,optional"`
	Switch   int    `json:"switch,optional"`
}

type DatasourceListResponse struct {
	Current  int              `json:"current"`
	PageSize int              `json:"pageSize"`
	Total    int64            `json:"total"`
	List     []DatasourceInfo `json:"list"`
}

type DatasourceInfo struct {
	Id         int    `json:"id"`
	Name       string `json:"name"`
	Type       string `json:"type"`
	Config     string `json:"config"`
	Switch     int    `json:"switch"`
	Hash       string `json:"hash"`
	Status     string `json:"status"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type DatasourceAddRequest struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	Config string `json:"config"`
	Switch int    `json:"switch"`
}

type DatasourceAddResponse struct {
	Id int `json:"id"`
}

type DatasourceEditRequest struct {
	Id     int    `json:"id"`
	Name   string `json:"name"`
	Type   string `json:"type,optional"`
	Config string `json:"config,optional"`
	Switch int    `json:"switch,optional"`
}

type DatasourceEditResponse struct {
	Id int `json:"id"`
}

type DatasourceDeleteRequest struct {
	Id int `json:"id"`
}

type DatasourceDeleteResponse struct {
	Id int `json:"id"`
}

type DatasourceTestRequest struct {
	Type   string `json:"type,optional"`
	Config string `json:"config,optional"`
}

type DatasourceTestResponse struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type User struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	RealName  string `json:"realName"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Status    int64  `json:"status"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	RoleId    int64  `json:"roleId"`
	RoleName  string `json:"roleName"`
	Password  string `json:"password"`
}

type UserLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginResponse struct {
	Token string `json:"token"`
}

type UserLogoutRequest struct {
}

type UserLogoutResponse struct {
}

type UserInfoRequest struct {
}

type UserInfoResponse struct {
	User     User   `json:"user"`
	RoleName string `json:"roleName"`
}

type UserRegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	RealName string `json:"realName,optional"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Status   int64  `json:"status,optional"`
}

type UserRegisterResponse struct {
	Token string `json:"token"`
}

type UserBindRoleRequest struct {
	UserId int64 `json:"userId"`
	RoleId int64 `json:"roleId"`
}

type UserBindRoleResponse struct {
}

type UserListRequest struct {
	Current  int64  `json:"current"`
	PageSize int64  `json:"pageSize"`
	Username string `json:"username,optional"`
}

type UserListResponse struct {
	Total int64  `json:"total"`
	List  []User `json:"list"`
}

type UserUpdateStatusRequest struct {
	UserId int64 `json:"userId"`
	Status int64 `json:"status" comment:"状态 1:正常 0:禁用"`
}

type UserUpdateStatusResponse struct {
}

type UserUpdateInfoRequest struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username,optional"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Password string `json:"password,optional"`
}

type UserUpdateInfoResponse struct {
}

type Role struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	Status      int64  `json:"status"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type CreateRoleRequest struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description,optional"`
	Status      int64  `json:"status,optional"`
}

type CreateRoleResponse struct {
	Id int64 `json:"id"`
}

type UpdateRoleRequest struct {
	Id          int64  `json:"id"`
	Name        string `json:"name,optional"`
	Code        string `json:"code,optional"`
	Description string `json:"description,optional"`
	Status      int64  `json:"status,optional"`
}

type UpdateRoleResponse struct {
}

type DeleteRoleRequest struct {
	Id int64 `json:"id"`
}

type DeleteRoleResponse struct {
}

type GetRoleRequest struct {
	Id int64 `json:"id"`
}

type GetRoleResponse struct {
	Role Role `json:"role"`
}

type ListRoleRequest struct {
	Current  int64  `json:"current"`
	PageSize int64  `json:"pageSize"`
	Name     string `json:"name,optional"`
}

type ListRoleResponse struct {
	Total int64  `json:"total"`
	List  []Role `json:"list"`
}

type BatchBindPermissionRequest struct {
	RoleId        int64   `json:"roleId"`
	PermissionIds []int64 `json:"permissionIds"`
}

type BatchBindPermissionResponse struct {
}

type BatchUnbindPermissionRequest struct {
	RoleId        int64   `json:"roleId"`
	PermissionIds []int64 `json:"permissionIds"`
}

type BatchUnbindPermissionResponse struct {
}

type GetRolePermissionRequest struct {
	RoleId int64 `json:"roleId"`
}

type GetRolePermissionResponse struct {
	RolePermissions []int64 `json:"rolePermissions"`
}

type Permission struct {
	Id        int64        `json:"id"`
	Title     string       `json:"title"`
	Key       string       `json:"key"`
	Type      int64        `json:"type"`
	ParentKey string       `json:"parentKey,optional"`
	Path      string       `json:"path,optional"`
	Method    string       `json:"method,optional"`
	Sort      int64        `json:"sort,optional"`
	CreatedAt string       `json:"createdAt"`
	UpdatedAt string       `json:"updatedAt"`
	Children  []Permission `json:"children,optional"`
}

type CreatePermissionRequest struct {
	Title     string `json:"title"`
	Key       string `json:"key"`
	Type      int64  `json:"type"`
	ParentKey string `json:"parentKey,optional"`
	Path      string `json:"path,optional"`
	Method    string `json:"method,optional"`
	Sort      int64  `json:"sort,optional"`
}

type CreatePermissionResponse struct {
	Id int64 `json:"id"`
}

type UpdatePermissionRequest struct {
	Key       string `json:"key"`
	Title     string `json:"title,optional"`
	Type      int64  `json:"type,optional"`
	ParentKey string `json:"parentKey,optional"`
	Path      string `json:"path,optional"`
	Method    string `json:"method,optional"`
	Sort      int64  `json:"sort,optional"`
}

type UpdatePermissionResponse struct {
}

type DeletePermissionRequest struct {
	Key string `json:"key"`
}

type DeletePermissionResponse struct {
}

type GetPermissionRequest struct {
	Key string `json:"key"`
}

type GetPermissionResponse struct {
	Permission Permission `json:"permission"`
}

type GetPermissionTreeRequest struct {
	ParentKey string `json:"parentKey,optional"`
}

type GetPermissionTreeResponse struct {
	List []Permission `json:"list"`
}

type GetPermissionListRequest struct {
	Title     string `json:"title,optional"`
	Key       string `json:"key,optional"`
	Type      int64  `json:"type,optional"`
	Method    string `json:"method,optional"`
	Path      string `json:"path,optional"`
	ParentKey string `json:"parentKey,optional"`
	Current   int64  `json:"current"`
	PageSize  int64  `json:"pageSize"`
}

type GetPermissionListResponse struct {
	List  []Permission `json:"list"`
	Total int64        `json:"total"`
}

type Kv struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type CreateKvRequest struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type CreateKvResponse struct {
}

type UpdateKvRequest struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type UpdateKvResponse struct {
}

type DeleteKvRequest struct {
	Key string `json:"key"`
}

type DeleteKvResponse struct {
}

type GetKvRequest struct {
	Key string `json:"key"`
}

type GetKvResponse struct {
	Kv Kv `json:"kv"`
}

type ListKvRequest struct {
	Current  int64  `json:"current"`
	PageSize int64  `json:"pageSize"`
	Key      string `json:"key,optional"`
}

type ListKvResponse struct {
	Total int64 `json:"total"`
	List  []Kv  `json:"list"`
}

type JobPublishRequest struct {
	WorkSpaceId string `json:"workSpaceId" desc:"空间ID"`
	JobName     string `json:"jobName" desc:"名称"`
	JobDesc     string `json:"jobDesc" desc:"描述"`
	JobCron     string `json:"jobCron" desc:"cron表达式"`
	JobParam    string `json:"jobParam" desc:"Job参数"`
}

type JobPublishResponse struct {
	JobId string `json:"jobId"`
}

type JobPublishListRequest struct {
	Current     int    `json:"current"`
	PageSize    int    `json:"pageSize"`
	WorkSpaceId string `json:"workSpaceId,optional"`
	JobName     string `json:"jobName,optional"`
}

type JobPublishListResponse struct {
	Current  int              `json:"current"`
	PageSize int              `json:"pageSize"`
	Total    int64            `json:"total"`
	List     []JobPublishList `json:"list"`
}

type JobPublishList struct {
	WorkSpaceId string `json:"workSpaceId"`
	JobId       string `json:"jobId"`
	JobName     string `json:"jobName"`
	JobDesc     string `json:"jobDesc"`
	JobCron     string `json:"jobCron"`
	JobParam    string `json:"jobParam"`
	Status      string `json:"status" desc:"状态 ON OFF"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type JobOnOffRequest struct {
	JobId  string `json:"jobId"`
	Status string `json:"status" desc:"状态 ON OFF"`
}

type JobOnOffResponse struct {
	JobId  string `json:"jobId"`
	Status string `json:"status" desc:"状态 ON OFF"`
}

type JobRecordsRequest struct {
	Current   int    `json:"current"`
	PageSize  int    `json:"pageSize"`
	JobId     string `json:"jobId,optional" desc:"jobId"`
	StartTime int64  `json:"startTime,optional" desc:"开始时间"`
	EndTime   int64  `json:"endTime,optional" desc:"结束时间"`
	Status    string `json:"status,optional" desc:"状态"`
}

type JobRecordsResponse struct {
	Current  int          `json:"current"`
	PageSize int          `json:"pageSize"`
	Total    int64        `json:"total"`
	List     []JobRecords `json:"list"`
}

type JobRecords struct {
	JobId    string `json:"jobId"`
	JobName  string `json:"jobName"`
	ExecTime string `json:"execTime"`
	Status   string `json:"status"`
	TraceId  string `json:"traceId"`
	Param    string `json:"param"`
	Result   string `json:"result"`
	ErrorMsg string `json:"errorMsg"`
	Duration int64  `json:"duration" desc:"执行时长(毫秒)"`
}

type JobHistoryRequest struct {
	WorkSpaceId string `json:"workSpaceId"`
	Current     int    `json:"current"`
	PageSize    int    `json:"pageSize"`
}

type JobHistoryResponse struct {
	Current  int          `json:"current"`
	PageSize int          `json:"pageSize"`
	Total    int64        `json:"total"`
	List     []JobHistory `json:"list"`
}

type JobHistory struct {
	Id          int64  `json:"id"`
	WorkSpaceId string `json:"workSpaceId"`
	JobName     string `json:"jobName"`
	CreateTime  string `json:"createTime"`
}

type JobEditRequest struct {
	JobId    string `json:"jobId"`
	JobCron  string `json:"jobCron"`
	JobParam string `json:"jobParam"`
	JobName  string `json:"jobName" desc:"名称"`
	JobDesc  string `json:"jobDesc" desc:"描述"`
}

type JobEditResponse struct {
	JobId string `json:"jobId"`
}
