### 画布-详情
POST http://127.0.0.1:8899/workflow/canvas/detail
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "workSpaceId": "crvpmf53sjtsppvoiogg"
}

### 画布-执行-全部
POST http://127.0.0.1:8899/workflow/canvas/run
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "id": "ctdbgr2flvkk9k4q7t7g"
}

### 画布-执行-单组件
POST http://127.0.0.1:8899/workflow/canvas/run/single
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "id": "ctdp4353sjtrlkhmrvb0",
  "nodeId": "jsTransform-530910c6-950d-4bda-b68d-90b0b4f4ddb0"
}


### 画布-更新
POST http://127.0.0.1:8899/workflow/canvas/draft
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "workSpaceId": "crvpmf53sjtsppvoiogg"
}

### 画布-执行记录
GET http://127.0.0.1:8899/workflow/canvas/run/history/asdasd
User-Agent: Apifox/1.0.0 (https://apifox.com)

### 画布-执行记录详情
GET http://127.0.0.1:8899/workflow/canvas/run/detail/22222
User-Agent: Apifox/1.0.0 (https://apifox.com)

### API-发布
POST http://127.0.0.1:8899/workflow/canvas/publish
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "id": "cs8vfql3sjtkvhkubulg",
  "apiName": "雪兔测试并行1",
  "apiDesc": "嘻嘻嘻 哈哈哈"
}


### 画布-执行-单组件详情
POST http://127.0.0.1:8899/workflow/canvas/run/single/detail
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "id": "ctdp4353sjtrlkhmrvb0",
  "nodeId": "jsTransform-af381ef9-cc1c-4419-89d7-a632482c9132"
}

### 画布-保存历史版本
POST http://127.0.0.1:8899/workflow/canvas/history/save
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "workspaceId": "crvpmf53sjtsppvoiogg",
  "name": "雪兔测试并行1"
}
    