-- Create "api" table
CREATE TABLE `api` (`id` int NOT NULL AUTO_INCREMENT, `workspace_id` varchar(255) NOT NULL, `api_id` varchar(255) NOT NULL, `api_name` varchar(255) NOT NULL, `api_desc` text NOT NULL, `dsl` json NOT NULL, `status` varchar(255) NOT NULL, `create_time` datetime NOT NULL, `update_time` datetime NOT NULL, `history_id` int NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `unidx_api_id` (`api_id`))   COMMENT "api服务表" AUTO_INCREMENT 38;
-- Create "api_record" table
CREATE TABLE `api_record` (`id` int NOT NULL AUTO_INCREMENT, `status` varchar(255) NOT NULL, `trace_id` varchar(255) NOT NULL, `param` json NOT NULL COMMENT "参数", `extend` json NOT NULL COMMENT "扩展", `call_time` datetime NOT NULL, `api_id` varchar(255) NOT NULL, `api_name` varchar(255) NOT NULL, `error_msg` longtext NOT NULL, `secrety_key` varchar(255) NOT NULL, PRIMARY KEY (`id`), INDEX `uni_api_id` (`api_id`))   COMMENT "api调用记录" AUTO_INCREMENT 59989;
-- Create "api_secret_key" table
CREATE TABLE `api_secret_key` (`id` int NOT NULL AUTO_INCREMENT, `secret_key` varchar(255) NOT NULL, `api_id` varchar(255) NOT NULL, `expiration_time` datetime NOT NULL, `status` varchar(255) NOT NULL COMMENT "ON、OFF", `is_deleted` int NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`), INDEX `nidx_api_id` (`api_id`), INDEX `nidx_secret_key` (`secret_key`))   COMMENT "api 密钥表" AUTO_INCREMENT 63;
-- Create "audit" table
CREATE TABLE `audit` (`id` int NOT NULL, `user_id` int NOT NULL, `code` varchar(255) NOT NULL, `request` longtext NOT NULL, `response` longtext NOT NULL, `create_time` datetime NOT NULL, `url` longtext NOT NULL)   COMMENT "操作审计表";
-- Create "canvas" table
CREATE TABLE `canvas` (`id` int NOT NULL AUTO_INCREMENT, `workspace_id` varchar(255) NOT NULL, `draft` json NOT NULL, `create_at` datetime NOT NULL, `update_at` datetime NOT NULL, `create_by` varchar(255) NOT NULL, `update_by` varchar(255) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `unidx_workspace_id` (`workspace_id`))   AUTO_INCREMENT 70;
-- Create "canvas_history" table
CREATE TABLE `canvas_history` (`id` int NOT NULL AUTO_INCREMENT, `workspace_id` varchar(255) NOT NULL, `draft` json NOT NULL, `name` varchar(255) NOT NULL, `create_time` datetime NOT NULL, `mode` int NOT NULL COMMENT "0-草稿 1-api 2-job", PRIMARY KEY (`id`))   COMMENT "画布历史表" AUTO_INCREMENT 48;
-- Create "datasource" table
CREATE TABLE `datasource` (`id` int NOT NULL AUTO_INCREMENT, `type` varchar(255) NOT NULL, `config` json NOT NULL, `switch` int NOT NULL, `hash` varchar(255) NOT NULL, `status` varchar(255) NOT NULL, `create_time` datetime NOT NULL, `update_time` datetime NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `un_name` (`name`) COMMENT "名称唯一索引")   AUTO_INCREMENT 45;
-- Create "job" table
CREATE TABLE `job` (`id` int NOT NULL AUTO_INCREMENT, `workspace_id` varchar(255) NOT NULL, `job_id` varchar(255) NOT NULL, `job_name` varchar(255) NOT NULL, `job_cron` varchar(255) NOT NULL, `job_desc` text NOT NULL, `dsl` json NOT NULL, `status` varchar(255) NOT NULL, `create_time` datetime NOT NULL, `update_time` datetime NOT NULL, `history_id` int NOT NULL, `params` json NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `unidx_job_id` (`job_id`))   COMMENT "job服务表" AUTO_INCREMENT 3;
-- Create "job_record" table
CREATE TABLE `job_record` (`id` int NOT NULL AUTO_INCREMENT, `status` varchar(255) NOT NULL, `trace_id` varchar(255) NOT NULL, `param` json NOT NULL COMMENT "参数", `result` json NOT NULL COMMENT "结果", `exec_time` datetime NOT NULL, `job_id` varchar(255) NOT NULL, `job_name` varchar(255) NOT NULL, `error_msg` longtext NOT NULL, `duration` int NOT NULL, PRIMARY KEY (`id`), INDEX `uni_job_id` (`job_id`))   COMMENT "job调用记录";
-- Create "kv" table
CREATE TABLE `kv` (`id` int NOT NULL AUTO_INCREMENT, `key` varchar(255) NOT NULL, `value` json NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `uni_key` (`key`))   AUTO_INCREMENT 5;
-- Create "module" table
CREATE TABLE `module` (`module_id` varchar(255) NOT NULL COMMENT "组件ID", `module_name` varchar(255) NOT NULL COMMENT "组件名称", `module_type` varchar(255) NOT NULL COMMENT "组件类型", `module_config` json NOT NULL COMMENT "组件配置", `module_index` int NOT NULL COMMENT "排序desc", PRIMARY KEY (`module_id`))   COMMENT "组件库";
-- Create "permissions" table
CREATE TABLE `permissions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `title` varchar(50) NOT NULL COMMENT "权限名称", `key` varchar(50) NOT NULL COMMENT "权限编码", `type` tinyint NOT NULL COMMENT "类型 1:菜单 2:按钮 3:接口", `parent_key` varchar(255) NULL COMMENT "父级Key", `path` varchar(200) NULL COMMENT "路径", `method` varchar(10) NULL COMMENT "HTTP方法", `sort` int NULL DEFAULT 0 COMMENT "排序", `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE INDEX `idx_key` (`key`))   COMMENT "权限表" AUTO_INCREMENT 141;
-- Create "role_permissions" table
CREATE TABLE `role_permissions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `role_id` bigint unsigned NOT NULL COMMENT "角色ID", `permission_id` bigint unsigned NOT NULL COMMENT "权限ID", `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE INDEX `idx_role_permission` (`role_id`, `permission_id`))   COMMENT "角色权限关联表" AUTO_INCREMENT 155;
-- Create "roles" table
CREATE TABLE `roles` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `name` varchar(50) NOT NULL COMMENT "角色名称", `code` varchar(50) NOT NULL COMMENT "角色编码", `description` varchar(200) NULL COMMENT "角色描述", `status` tinyint NOT NULL DEFAULT 1 COMMENT "状态 1:启用 0:禁用", `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE INDEX `idx_code` (`code`))   COMMENT "角色表" AUTO_INCREMENT 36;
-- Create "space_record" table
CREATE TABLE `space_record` (`id` int NOT NULL AUTO_INCREMENT, `workspace_id` varchar(255) NOT NULL COMMENT "空间 ID", `status` varchar(255) NOT NULL COMMENT "运行状态", `serial_number` varchar(255) NOT NULL COMMENT "流水号", `run_time` datetime NOT NULL COMMENT "运行开始时间", `record_name` varchar(255) NOT NULL COMMENT "运行记录名称", `duration` int NOT NULL COMMENT "耗时 ms", `other` json NOT NULL COMMENT "其他配置", PRIMARY KEY (`id`), UNIQUE INDEX `unidx_serial_number` (`serial_number`), INDEX `unidx_workspace_id` (`workspace_id`))   AUTO_INCREMENT 719;
-- Create "trace" table
CREATE TABLE `trace` (`id` int NOT NULL AUTO_INCREMENT, `workspace_id` varchar(255) NOT NULL COMMENT "空间 ID", `trace_id` varchar(255) NOT NULL COMMENT "追踪 ID", `input` json NOT NULL COMMENT "组件输入", `logic` json NOT NULL COMMENT "执行逻辑", `output` json NOT NULL COMMENT "组件输出", `step` int NOT NULL COMMENT "分步", `node_id` varchar(255) NOT NULL COMMENT "节点 ID", `node_name` varchar(255) NOT NULL COMMENT "节点名称", `status` varchar(255) NOT NULL COMMENT "运行状态", `elapsed_time` int NOT NULL COMMENT "运行耗时", `start_time` datetime NOT NULL COMMENT "执行时间", `error_msg` longtext NOT NULL, PRIMARY KEY (`id`), INDEX `unidx_trace_id` (`trace_id`), INDEX `unidx_workspace_id` (`workspace_id`))   COMMENT "组件链路追踪记录表" AUTO_INCREMENT 144611;
-- Create "user_roles" table
CREATE TABLE `user_roles` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint unsigned NOT NULL COMMENT "用户ID", `role_id` bigint unsigned NOT NULL COMMENT "角色ID", `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE INDEX `idx_user_role` (`user_id`, `role_id`))   COMMENT "用户角色关联表" AUTO_INCREMENT 3;
-- Create "users" table
CREATE TABLE `users` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `username` varchar(50) NOT NULL COMMENT "用户名", `password` varchar(100) NOT NULL COMMENT "密码", `salt` varchar(20) NOT NULL COMMENT "密码盐", `real_name` varchar(50) NULL COMMENT "真实姓名", `phone` varchar(20) NULL COMMENT "手机号", `email` varchar(100) NULL COMMENT "邮箱", `status` tinyint NOT NULL DEFAULT 1 COMMENT "状态 1:启用 0:禁用", `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE INDEX `idx_username` (`username`))   COMMENT "用户表" AUTO_INCREMENT 3;
-- Create "workspace" table
CREATE TABLE `workspace` (`id` int NOT NULL AUTO_INCREMENT COMMENT "自增主建", `workspace_id` varchar(255) NOT NULL COMMENT "主建", `workspace_name` varchar(255) NOT NULL COMMENT "名称", `workspace_desc` text NULL COMMENT "描述", `workspace_type` varchar(50) NULL COMMENT "类型flow|agent", `workspace_icon` varchar(255) NULL COMMENT "iconUrl", `canvas_config` text NULL COMMENT "前端画布配置", `configuration` json NOT NULL COMMENT "配置信息 KV", `additionalInfo` json NOT NULL COMMENT "扩展信息", `create_time` datetime NOT NULL COMMENT "创建时间", `update_time` datetime NOT NULL COMMENT "修改时间", `is_delete` int NOT NULL DEFAULT 0 COMMENT "是否删除", PRIMARY KEY (`id`), UNIQUE INDEX `unique_workspace_id` (`workspace_id`))   COMMENT "工作空间表" AUTO_INCREMENT 72;
-- Create "workspace_tag" table
CREATE TABLE `workspace_tag` (`id` int NOT NULL AUTO_INCREMENT COMMENT "自增主建", `tag_name` varchar(255) NOT NULL COMMENT "标签名称", `is_delete` int NOT NULL COMMENT "逻辑删除", `create_time` datetime NOT NULL COMMENT "创建时间", `update_time` datetime NOT NULL COMMENT "修改时间", PRIMARY KEY (`id`), INDEX `idx_tag_name` (`tag_name`))   COMMENT "标签表" AUTO_INCREMENT 34;
-- Create "workspace_tag_mapping" table
CREATE TABLE `workspace_tag_mapping` (`id` int NOT NULL AUTO_INCREMENT COMMENT "主建", `tag_id` int NOT NULL COMMENT "标签ID", `workspace_id` varchar(255) NOT NULL COMMENT "画布空间ID", PRIMARY KEY (`id`), INDEX `idx_tag_id` (`tag_id`), INDEX `idx_worlspace_id` (`workspace_id`))   COMMENT "画布标签映射表" AUTO_INCREMENT 91;

// 写入组件
INSERT INTO module (`module_id`,`module_name`,`module_type`,`module_config`,`module_index`) VALUES ('0def1c72-a83f-43a6-b6b1-c4a4c589d16b','执行代码','process','{\"type\": \"jsTransform\", \"point\": {\"inputs\": [{\"id\": \"input\", \"type\": \"target\", \"color\": \"blue\", \"label\": \"输入数据\", \"position\": \"left\", \"handleType\": \"Data\"}], \"outputs\": [{\"id\": \"Success\", \"type\": \"source\", \"color\": \"green\", \"label\": \"成功\", \"position\": \"right\", \"handleType\": \"Success\"}, {\"id\": \"Failure\", \"type\": \"source\", \"color\": \"red\", \"label\": \"失败\", \"position\": \"right\", \"handleType\": \"Failure\"}]}, \"fields\": [{\"id\": \"jsScript\", \"type\": \"code-input\", \"label\": \"处理脚本\", \"config\": {\"theme\": \"vs-dark\", \"height\": 200, \"options\": {\"minimap\": {\"enabled\": false}, \"fontSize\": 14, \"lineNumbers\": true}, \"language\": \"javascript\", \"defaultValue\": \"function Filter(msg, metadata, msgType) {  \\n  return { msg: msg, metadata: metadata, msgType: msgType };\\n}\"}}], \"runnable\": true}',5);
INSERT INTO module (`module_id`,`module_name`,`module_type`,`module_config`,`module_index`) VALUES ('0e36fd17-1f91-44d7-b124-346194e7f031','开始','input','{\"type\": \"start\", \"point\": {\"inputs\": [], \"outputs\": [{\"id\": \"Success\", \"type\": \"source\", \"color\": \"green\", \"label\": \"成功\", \"position\": \"right\", \"handleType\": \"Success\"}]}, \"fields\": [{\"id\": \"param\", \"type\": \"json-input\", \"label\": \"请求头\", \"config\": {\"height\": 150, \"defaultValue\": \"{\\\"root\\\": \\\"start\\\"}\"}}]}',1);
INSERT INTO module (`module_id`,`module_name`,`module_type`,`module_config`,`module_index`) VALUES ('11366510-4985-4db8-aab2-3c3500ec4f4e','条件','process','{\"type\": \"jsFilter\", \"point\": {\"inputs\": [{\"id\": \"input\", \"type\": \"target\", \"color\": \"blue\", \"label\": \"输入数据\", \"position\": \"left\", \"handleType\": \"Data\"}], \"outputs\": [{\"id\": \"True\", \"type\": \"source\", \"color\": \"green\", \"label\": \"True\", \"position\": \"right\", \"handleType\": \"True\"}, {\"id\": \"False\", \"type\": \"source\", \"color\": \"orange\", \"label\": \"False\", \"position\": \"right\", \"handleType\": \"False\"}, {\"id\": \"Failure\", \"type\": \"source\", \"color\": \"red\", \"label\": \"失败\", \"position\": \"right\", \"handleType\": \"Failure\"}]}, \"fields\": [{\"id\": \"jsScript\", \"type\": \"input\", \"label\": \"判断条件\", \"config\": {\"height\": 150, \"defaultValue\": \"msg.?==1\"}}]}',3);
INSERT INTO module (`module_id`,`module_name`,`module_type`,`module_config`,`module_index`) VALUES ('3c2a2245-480f-4ffb-871e-11b1389a27bf','结束','output','{\"type\": \"end\", \"point\": {\"inputs\": [{\"id\": \"input\", \"type\": \"target\", \"color\": \"blue\", \"label\": \"输入数据\", \"position\": \"left\", \"handleType\": \"Data\"}]}, \"fields\": []}',2);
INSERT INTO module (`module_id`,`module_name`,`module_type`,`module_config`,`module_index`) VALUES ('789a7fc1-9ba9-4805-9dbe-a16f69b1920d','聚合','output','{\"type\": \"join\", \"point\": {\"inputs\": [{\"id\": \"input\", \"type\": \"target\", \"color\": \"blue\", \"label\": \"输入数据\", \"position\": \"left\", \"handleType\": \"Data\"}], \"outputs\": [{\"id\": \"Success\", \"type\": \"source\", \"color\": \"green\", \"label\": \"成功\", \"position\": \"right\", \"handleType\": \"Success\"}, {\"id\": \"Failure\", \"type\": \"source\", \"color\": \"red\", \"label\": \"失败\", \"position\": \"right\", \"handleType\": \"Failure\"}]}, \"fields\": []}',8);
INSERT INTO module (`module_id`,`module_name`,`module_type`,`module_config`,`module_index`) VALUES ('83caa852-1041-4acb-8ddf-90aa7340e99d','数据库','output','{\"type\": \"database\", \"point\": {\"inputs\": [{\"id\": \"input\", \"type\": \"target\", \"color\": \"blue\", \"label\": \"输入数据\", \"position\": \"left\", \"handleType\": \"Data\"}], \"outputs\": [{\"id\": \"Success\", \"type\": \"source\", \"color\": \"green\", \"label\": \"成功\", \"position\": \"right\", \"handleType\": \"Success\"}, {\"id\": \"Failure\", \"type\": \"source\", \"color\": \"red\", \"label\": \"失败\", \"position\": \"right\", \"handleType\": \"Failure\"}]}, \"fields\": [{\"id\": \"datasource_type\", \"type\": \"radio\", \"label\": \"数据库类型\", \"config\": {\"options\": [{\"label\": \"MySQL\", \"value\": \"MySQL\"}, {\"label\": \"SqlServer\", \"value\": \"SqlServer\"}], \"defaultValue\": \"MySQL\"}}, {\"id\": \"datasource_id\", \"type\": \"number\", \"label\": \"数据源 ID\", \"config\": {\"height\": 150, \"defaultValue\": 0}}, {\"id\": \"datasource_sql\", \"type\": \"sql-input\", \"label\": \"SQL语句\", \"config\": {\"height\": 150, \"defaultValue\": \"select * from users where id = ${msg.id} and name = ${msg.name} limit 10;\"}}], \"runnable\": true}',13);
INSERT INTO module (`module_id`,`module_name`,`module_type`,`module_config`,`module_index`) VALUES ('89a43296-6f1f-4a17-b5c2-e9a2c3a7affd','HTTP-XML','output','{\"type\": \"http-xml\", \"point\": {\"inputs\": [{\"id\": \"input\", \"type\": \"target\", \"color\": \"blue\", \"label\": \"输入数据\", \"position\": \"left\", \"handleType\": \"Data\"}], \"outputs\": [{\"id\": \"Success\", \"type\": \"source\", \"color\": \"green\", \"label\": \"成功\", \"position\": \"right\", \"handleType\": \"Success\"}, {\"id\": \"Failure\", \"type\": \"source\", \"color\": \"red\", \"label\": \"失败\", \"position\": \"right\", \"handleType\": \"Failure\"}]}, \"fields\": [{\"id\": \"method\", \"type\": \"radio\", \"label\": \"请求类型\", \"config\": {\"options\": [{\"label\": \"POST\", \"value\": \"post\"}], \"defaultValue\": \"post\"}}, {\"id\": \"url\", \"type\": \"input\", \"label\": \"地址\", \"config\": {\"height\": 150, \"defaultValue\": \"http://\"}}, {\"id\": \"header\", \"type\": \"dy-form\", \"label\": \"请求头\", \"config\": {\"height\": 150, \"defaultValue\": [{\"label\": \"Content-Type\", \"value\": \"application/json\"}]}}, {\"id\": \"xmlParam\", \"type\": \"xml-input\", \"label\": \"请求参数\", \"config\": {\"theme\": \"vs-dark\", \"height\": 200, \"options\": {\"minimap\": {\"enabled\": false}, \"fontSize\": 14, \"lineNumbers\": true}, \"language\": \"xml\", \"defaultValue\": \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?><person><name>张三</name><age>25</age></person>\"}}], \"runnable\": true}',12);
INSERT INTO module (`module_id`,`module_name`,`module_type`,`module_config`,`module_index`) VALUES ('8d72d9aa-e4eb-40ba-94c1-8e269afb607b','HTTP','output','{\"type\": \"http\", \"point\": {\"inputs\": [{\"id\": \"input\", \"type\": \"target\", \"color\": \"blue\", \"label\": \"输入数据\", \"position\": \"left\", \"handleType\": \"Data\"}], \"outputs\": [{\"id\": \"Success\", \"type\": \"source\", \"color\": \"green\", \"label\": \"成功\", \"position\": \"right\", \"handleType\": \"Success\"}, {\"id\": \"Failure\", \"type\": \"source\", \"color\": \"red\", \"label\": \"失败\", \"position\": \"right\", \"handleType\": \"Failure\"}]}, \"fields\": [{\"id\": \"method\", \"type\": \"radio\", \"label\": \"请求类型\", \"config\": {\"options\": [{\"label\": \"GET\", \"value\": \"get\"}, {\"label\": \"POST\", \"value\": \"post\"}], \"defaultValue\": \"post\"}}, {\"id\": \"url\", \"type\": \"input\", \"label\": \"地址\", \"config\": {\"height\": 150, \"defaultValue\": \"http://\"}}, {\"id\": \"header\", \"type\": \"dy-form\", \"label\": \"请求头\", \"config\": {\"height\": 150, \"defaultValue\": [{\"label\": \"Content-Type\", \"value\": \"application/json\"}]}}], \"runnable\": true}',11);
INSERT INTO module (`module_id`,`module_name`,`module_type`,`module_config`,`module_index`) VALUES ('8fb6bee3-9e88-4c02-a25e-840ebf1f73b6','并发','input','{\"type\": \"fork\", \"point\": {\"inputs\": [{\"id\": \"input\", \"type\": \"target\", \"color\": \"blue\", \"label\": \"输入数据\", \"position\": \"left\", \"handleType\": \"Data\"}], \"outputs\": [{\"id\": \"Success\", \"type\": \"source\", \"color\": \"green\", \"label\": \"成功\", \"position\": \"right\", \"handleType\": \"Success\"}]}, \"fields\": []}',7);
INSERT INTO module (`module_id`,`module_name`,`module_type`,`module_config`,`module_index`) VALUES ('95bff99e-4b9c-4afd-94ca-9615351ef057','迭代','process','{\"type\": \"for\", \"point\": {\"inputs\": [{\"id\": \"input\", \"type\": \"target\", \"color\": \"blue\", \"label\": \"输入数据\", \"position\": \"left\", \"handleType\": \"Data\"}], \"outputs\": [{\"id\": \"Do\", \"type\": \"source\", \"color\": \"blue\", \"label\": \"迭代\", \"position\": \"right\", \"handleType\": \"Do\"}, {\"id\": \"Success\", \"type\": \"source\", \"color\": \"green\", \"label\": \"成功\", \"position\": \"right\", \"handleType\": \"Success\"}, {\"id\": \"Failure\", \"type\": \"source\", \"color\": \"red\", \"label\": \"失败\", \"position\": \"right\", \"handleType\": \"Failure\"}]}, \"fields\": [{\"id\": \"range\", \"type\": \"input\", \"label\": \"迭代对象\", \"config\": {\"height\": 150, \"defaultValue\": \"msg.?\"}}]}',4);
INSERT INTO module (`module_id`,`module_name`,`module_type`,`module_config`,`module_index`) VALUES ('bc6963b0-2fbc-4104-b9e0-3f22f1f8c8fd','文件服务器','output','{\"type\": \"fileServer\", \"point\": {\"inputs\": [{\"id\": \"input\", \"type\": \"target\", \"color\": \"blue\", \"label\": \"输入数据\", \"position\": \"left\", \"handleType\": \"Data\"}], \"outputs\": [{\"id\": \"Success\", \"type\": \"source\", \"color\": \"green\", \"label\": \"成功\", \"position\": \"right\", \"handleType\": \"Success\"}, {\"id\": \"Failure\", \"type\": \"source\", \"color\": \"red\", \"label\": \"失败\", \"position\": \"right\", \"handleType\": \"Failure\"}]}, \"fields\": [{\"id\": \"datasource_type\", \"type\": \"radio\", \"label\": \"文件系统类型\", \"config\": {\"options\": [{\"label\": \" SFTP\", \"value\": \"sftp\"}, {\"label\": \"FTP\", \"value\": \"ftp\"}], \"defaultValue\": \"ftp\"}}, {\"id\": \"datasource_mode\", \"type\": \"radio\", \"label\": \"操作模式\", \"config\": {\"options\": [{\"label\": \"上传\", \"value\": \"upload\"}, {\"label\": \"下载\", \"value\": \"download\"}, {\"label\": \"删除\", \"value\": \"delete\"}], \"defaultValue\": \"upload\"}}, {\"id\": \"datasource_id\", \"type\": \"number\", \"label\": \"数据源 ID\", \"config\": {\"height\": 150, \"defaultValue\": 0}}, {\"id\": \"datasource_path\", \"type\": \"input\", \"label\": \"路径\", \"config\": {\"height\": 150, \"defaultValue\": \"/data/xxx.xxx\"}}], \"runnable\": true}',14);

// 写入默认权限
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (1,'系统权限','root',1,'/',null,null,9999,'2025-01-04 17:41:19','2025-01-06 10:17:08');
// 写入默认用户
INSERT INTO users (`id`,`username`,`password`,`salt`,`real_name`,`phone`,`email`,`status`,`created_at`,`updated_at`) VALUES (1,'admin','3c3d20cf4936b81600306b09ab1f6cf4','21232f297a57a5a74',null,null,null,1,'2024-12-31 13:58:23','2025-01-04 15:00:50');
// 写入角色
INSERT INTO roles (`id`,`name`,`code`,`description`,`status`,`created_at`,`updated_at`) VALUES (33,'管理员','guanliyuan','guanliyuan',1,'2025-01-07 15:29:54','2025-01-07 15:29:54');
// 写入用户角色
INSERT INTO user_roles (`id`,`user_id`,`role_id`,`created_at`) VALUES (1,1,33,'2025-01-01 00:00:00');
// 写入权限
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (1,'系统权限','root',1,'/',null,null,9999,'2025-01-04 17:41:19','2025-01-06 10:17:08');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (57,'Workspace 管理','workspace_management',1,'root',null,null,9999,'2025-01-09 02:43:05','2025-01-09 02:46:10');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (58,'Tag 管理','tag_management',1,'root',null,null,9998,'2025-01-09 02:43:05','2025-01-09 02:46:10');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (59,'Mock 管理','mock_management',1,'root',null,null,9997,'2025-01-09 02:43:05','2025-01-09 02:46:10');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (60,'画布管理','canvas_management',1,'root',null,null,9996,'2025-01-09 02:43:05','2025-01-09 02:46:10');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (61,'API 管理','api_management',1,'root',null,null,9995,'2025-01-09 02:43:05','2025-01-09 02:46:10');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (62,'组件管理','module_management',1,'root',null,null,9994,'2025-01-09 02:43:05','2025-01-09 02:46:10');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (63,'数据源管理','datasource_management',1,'root',null,null,9993,'2025-01-09 02:43:05','2025-01-09 02:46:10');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (64,'用户管理','user_management',1,'root',null,null,9992,'2025-01-09 02:43:05','2025-01-09 02:46:10');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (65,'角色管理','role_management',1,'root',null,null,9991,'2025-01-09 02:43:05','2025-01-09 02:46:10');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (66,'权限管理','permission_management',1,'root',null,null,9990,'2025-01-09 02:43:05','2025-01-09 02:46:10');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (67,'键值对管理','kv_management',1,'root',null,null,9989,'2025-01-09 02:43:05','2025-01-09 02:46:10');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (68,'创建 workspace','create_workspace',3,'workspace_management','/workflow/workspace/new','POST',9999,'2025-01-09 02:57:43','2025-01-09 02:57:43');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (69,'删除 workspace','delete_workspace',3,'workspace_management','/workflow/workspace/remove','POST',9998,'2025-01-09 02:57:43','2025-01-09 02:57:43');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (70,'编辑 workspace','edit_workspace',3,'workspace_management','/workflow/workspace/edit','POST',9997,'2025-01-09 02:57:43','2025-01-09 02:57:43');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (71,'列表 workspace','list_workspace',3,'workspace_management','/workflow/workspace/list','POST',9996,'2025-01-09 02:57:43','2025-01-09 02:57:43');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (72,'编辑 workspace 标签','edit_workspace_tag',3,'workspace_management','/workflow/workspace/edit/tag','POST',9995,'2025-01-09 02:57:43','2025-01-09 02:57:43');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (73,'Workspace 复制','copy_workspace',3,'workspace_management','/workflow/workspace/copy','POST',9994,'2025-01-09 02:57:43','2025-01-09 02:57:43');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (74,'画布环境变量列表','list_workspace_env',3,'workspace_management','/workflow/workspace/env/list','POST',9993,'2025-01-09 02:57:43','2025-01-09 02:57:43');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (75,'画布环境变量修改','edit_workspace_env',3,'workspace_management','/workflow/workspace/env/edit','POST',9992,'2025-01-09 02:57:43','2025-01-09 02:57:43');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (76,'列表 tag','list_tag',3,'tag_management','/workflow/tag/list','POST',9991,'2025-01-09 02:57:43','2025-01-09 02:57:43');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (77,'编辑标签','edit_tag',3,'tag_management','/workflow/tag/edit','POST',9990,'2025-01-09 02:57:43','2025-01-09 02:57:43');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (78,'删除标签','delete_tag',3,'tag_management','/workflow/tag/remove','POST',9989,'2025-01-09 02:57:43','2025-01-09 02:57:43');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (79,'Mock 接口','mock_api',3,'mock_management','/workflow/mock','POST',9988,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (80,'画布更新','update_canvas',3,'canvas_management','/workflow/canvas/draft','POST',9987,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (81,'画布详情','get_canvas_detail',3,'canvas_management','/workflow/canvas/detail','POST',9986,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (82,'全部运行','run_canvas',3,'canvas_management','/workflow/canvas/run','POST',9985,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (83,'单组件运行','run_canvas_single',3,'canvas_management','/workflow/canvas/run/single','POST',9984,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (84,'组件运行详情','get_canvas_run_detail',3,'canvas_management','/workflow/canvas/run/single/detail','POST',9983,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (85,'获取画布运行历史','get_canvas_run_history',3,'canvas_management','/workflow/canvas/run/history/:id','GET',9982,'2025-01-09 02:57:44','2025-01-13 02:43:02');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (86,'获取画布运行详情','get_canvas_run_record_detail',3,'canvas_management','/workflow/canvas/run/detail/:id','GET',9981,'2025-01-09 02:57:44','2025-01-13 02:43:02');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (87,'保存历史版本','save_canvas_history',3,'canvas_management','/workflow/canvas/history/save','POST',9980,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (88,'获取历史版本列表','list_canvas_history',3,'canvas_management','/workflow/canvas/history/list','POST',9979,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (89,'恢复历史版本','restore_canvas_history',3,'canvas_management','/workflow/canvas/history/restore','POST',9978,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (90,'API 发布','publish_api',3,'api_management','/workflow/api/publish','POST',9977,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (91,'API 发布列表','list_api_publish',3,'api_management','/workflow/api/list','POST',9976,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (92,'API 上下线','toggle_api_status',3,'api_management','/workflow/api/onoff','POST',9975,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (93,'API 调用记录','list_api_records',3,'api_management','/workflow/api/records','POST',9974,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (94,'secretKey 列表','list_api_secret_keys',3,'api_management','/workflow/api/secretkey/list','POST',9973,'2025-01-09 02:57:44','2025-01-09 02:57:44');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (95,'创建 API 密钥','create_api_secret_key',3,'api_management','/workflow/api/secretkey/create','POST',9972,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (96,'修改 API 密钥状态','update_api_secret_key_status',3,'api_management','/workflow/api/secretkey/update/status','POST',9971,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (97,'修改 API 密钥到期时间','update_api_secret_key_expiration',3,'api_management','/workflow/api/secretkey/update/expirationtime','POST',9970,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (98,'删除 API 密钥','delete_api_secret_key',3,'api_management','/workflow/api/secretkey/delete','POST',9969,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (99,'API 历史版本','list_api_history',3,'api_management','/workflow/api/history','POST',9968,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (100,'组件 list','list_modules',3,'module_management','/workflow/module/list','POST',9967,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (101,'组件新建','create_module',3,'module_management','/workflow/module/new','POST',9966,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (102,'组件编辑','edit_module',3,'module_management','/workflow/module/edit','POST',9965,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (103,'数据源列表','list_datasources',3,'datasource_management','/workflow/datasource/list','POST',9964,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (104,'新增数据源','add_datasource',3,'datasource_management','/workflow/datasource/add','POST',9963,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (105,'编辑数据源','edit_datasource',3,'datasource_management','/workflow/datasource/edit','POST',9962,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (106,'删除数据源','delete_datasource',3,'datasource_management','/workflow/datasource/delete','POST',9961,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (107,'测试数据源','test_datasource',3,'datasource_management','/workflow/datasource/test','POST',9960,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (108,'用户登录','user_login',3,'user_management','/workflow/user/login','POST',9959,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (109,'用户信息','get_user_info',3,'user_management','/workflow/user/info','POST',9958,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (110,'用户注册','user_register',3,'user_management','/workflow/user/register','POST',9957,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (111,'用户退出登录','user_logout',3,'user_management','/workflow/user/logout','POST',9956,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (112,'获取用户列表','list_users',3,'user_management','/workflow/user/list','POST',9955,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (113,'绑定角色','bind_role_to_user',3,'user_management','/workflow/user/bindrole','POST',9954,'2025-01-09 02:57:45','2025-01-09 02:57:45');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (114,'修改用户状态','update_user_status',3,'user_management','/workflow/user/update/status','POST',9953,'2025-01-09 02:57:46','2025-01-09 02:57:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (115,'更新用户信息','update_user_info',3,'user_management','/workflow/user/update/info','POST',9952,'2025-01-09 02:57:46','2025-01-09 02:57:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (116,'创建角色','create_role',3,'role_management','/workflow/role/create','POST',9951,'2025-01-09 02:57:46','2025-01-09 02:57:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (117,'更新角色','update_role',3,'role_management','/workflow/role/update','POST',9950,'2025-01-09 02:57:46','2025-01-09 02:57:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (118,'删除角色','delete_role',3,'role_management','/workflow/role/delete','POST',9949,'2025-01-09 02:57:46','2025-01-09 02:57:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (119,'获取角色详情','get_role_detail',3,'role_management','/workflow/role/get','POST',9948,'2025-01-09 02:57:46','2025-01-09 02:57:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (120,'获取角色列表','list_roles',3,'role_management','/workflow/role/list','POST',9947,'2025-01-09 02:57:46','2025-01-09 02:57:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (121,'绑定权限','bind_permission_to_role',3,'role_management','/workflow/role/batchbindpermission','POST',9946,'2025-01-09 02:57:46','2025-01-09 06:51:39');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (123,'获取角色权限','get_role_permissions',3,'role_management','/workflow/role/getpermission','POST',9944,'2025-01-09 02:57:46','2025-01-09 02:57:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (124,'创建权限','create_permission',3,'permission_management','/workflow/permission/create','POST',9943,'2025-01-09 02:57:46','2025-01-09 02:57:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (125,'更新权限','update_permission',3,'permission_management','/workflow/permission/update','POST',9942,'2025-01-09 02:57:47','2025-01-09 02:57:47');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (126,'删除权限','delete_permission',3,'permission_management','/workflow/permission/delete','POST',9941,'2025-01-09 02:57:47','2025-01-09 02:57:47');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (127,'获取权限详情','get_permission_detail',3,'permission_management','/workflow/permission/get','POST',9940,'2025-01-09 02:57:47','2025-01-09 02:57:47');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (128,'获取权限树','get_permission_tree',3,'permission_management','/workflow/permission/tree','POST',9939,'2025-01-09 02:57:47','2025-01-09 02:57:47');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (129,'权限列表','list_permissions',3,'permission_management','/workflow/permission/list','POST',9938,'2025-01-09 02:57:47','2025-01-09 02:57:47');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (130,'创建键值对','create_kv',3,'kv_management','/workflow/kv/create','POST',9937,'2025-01-09 02:57:47','2025-01-09 02:57:47');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (131,'更新键值对','update_kv',3,'kv_management','/workflow/kv/update','POST',9936,'2025-01-09 02:57:47','2025-01-09 02:57:47');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (132,'删除键值对','delete_kv',3,'kv_management','/workflow/kv/delete','POST',9935,'2025-01-09 02:57:47','2025-01-09 02:57:47');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (133,'获取键值对详情','get_kv_detail',3,'kv_management','/workflow/kv/get','POST',9934,'2025-01-09 02:57:47','2025-01-09 02:57:47');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (134,'获取键值对列表','list_kv',3,'kv_management','/workflow/kv/list','POST',9933,'2025-01-09 02:57:47','2025-01-09 02:57:47');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (135,'Job发布','job_publish',3,'job_management','/workflow/job/publish','POST',9988,'2025-01-09 02:43:05','2025-01-13 03:04:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (136,'Job列表','job_list',3,'job_management','/workflow/job/list','POST',9987,'2025-01-09 02:43:05','2025-01-13 03:04:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (137,'Job上下线','job_on_off',3,'job_management','/workflow/job/onoff','POST',9986,'2025-01-09 02:43:05','2025-01-13 03:04:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (138,'Job执行记录','job_records',3,'job_management','/workflow/job/records','POST',9985,'2025-01-09 02:43:05','2025-01-13 03:04:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (139,'Job历史版本','job_history',3,'job_management','/workflow/job/history','POST',9984,'2025-01-09 02:43:05','2025-01-13 03:04:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (140,'JOB管理','job_management',1,'root',null,null,9987,'2025-01-09 02:43:05','2025-01-09 02:43:05');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (141,'Job编辑','job_edit',3,'job_management','/workflow/job/edit','POST',9983,'2025-01-09 02:43:05','2025-01-13 03:04:46');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (142,'API 调用','api_call',3,'api_management','/workflow/api/call','POST',9999,'2025-01-15 18:58:31','2025-01-15 18:58:31');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (143,'API 调用模板','api_call_template',3,'api_management','/workflow/api/call/template','POST',9999,'2025-01-15 18:59:14','2025-01-15 18:59:14');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (144,'API导出 CURL','api_export_curl',3,'api_management','/workflow/api/export/curl','POST',9999,'2025-01-15 19:00:03','2025-01-15 19:00:03');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (145,'导出 workspace','workspace_export',3,'workspace_management','/workflow/workspace/export','POST',9999,'2025-01-16 00:01:07','2025-01-16 00:01:07');
INSERT INTO permissions (`id`,`title`,`key`,`type`,`parent_key`,`path`,`method`,`sort`,`created_at`,`updated_at`) VALUES (146,'导入 workspace','workspace_Import',3,'workspace_management','/workflow/workspace/import','POST',9999,'2025-01-16 00:01:54','2025-01-16 00:01:54');


// 写入角色权限
INSERT INTO `role_permissions` (role_id,`permission_id`) SELECT 33,id FROM `permissions`;