---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: node
    meta.helm.sh/release-namespace: uat-43
  labels:
    app: workflow
    app.kubernetes.io/managed-by: Helm
    group: middleware
  name: workflow
  namespace: uat-43
  resourceVersion: '497376722'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: workflow
      group: middleware
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: workflow
        group: middleware
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - share-83
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - workflow
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: '8899'
            - name: LOG_MODE
              value: file
            - name: LOG_PATH
              value: /app/logs
            - name: MYSQL_DATASOURCE
              value: >-
                root:Root@123@tcp(ido-mysql-headless:3306)/workflow?charset=utf8mb4&parseTime=True&loc=Local
            - name: TELEMETRY_ENDPOINT
              value: 'openobserve:5081'
            - name: TELEMETRY_AUTHORIZATION
              value: Basic cm9vdEAxMjM0NTY3ODkuY29tOkNRY1Y0WHFpaWtVR255TEw=
            - name: OPENOB_PATH
              value: 'http://openobserve:5080/api/default/workflow/_json'
            - name: OPENOB_USERNAME
              value: root@123456789.com
            - name: OPENOB_PASSWORD
              value: '123456789'
          image: '10.12.0.78:5000/middleware-dev/workflow:dev-2.0.0-ccad156'
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 24
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8899
            timeoutSeconds: 5
          name: ccc
          readinessProbe:
            failureThreshold: 24
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8899
            timeoutSeconds: 5
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /glite/data/
              name: data
              subPath: middleware-gaia_lite
            - mountPath: /app/etc
              name: workflow-api
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gaia
        - configMap:
            defaultMode: 420
            name: workflow-api.yaml
          name: workflow-api
status:
  conditions:
    - lastTransitionTime: '2024-12-10T10:47:47Z'
      lastUpdateTime: '2024-12-10T10:47:47Z'
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: 'False'
      type: Available
    - lastTransitionTime: '2024-12-10T10:02:28Z'
      lastUpdateTime: '2024-12-10T11:06:03Z'
      message: ReplicaSet "workflow-778b8b4b77" is progressing.
      reason: ReplicaSetUpdated
      status: 'True'
      type: Progressing
  observedGeneration: 34
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: node
    meta.helm.sh/release-namespace: uat-43
  labels:
    app: workflow
    app.kubernetes.io/managed-by: Helm
    group: middleware
  name: workflow
  namespace: uat-43
  resourceVersion: '461625058'
spec:
  clusterIP: 10.99.43.99
  clusterIPs:
    - 10.99.43.99
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp8899
      nodePort: 14005
      port: 8899
      protocol: TCP
      targetPort: 8899
    - name: tcp9999
      nodePort: 26874
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: workflow
    group: middleware
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: node
    meta.helm.sh/release-namespace: uat-43
  labels:
    app: workflow
    app.kubernetes.io/managed-by: Helm
    group: middleware
  name: workflow
  namespace: uat-43
  resourceVersion: '461625058'
spec:
  clusterIP: 10.99.43.99
  clusterIPs:
    - 10.99.43.99
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp8899
      nodePort: 14005
      port: 8899
      protocol: TCP
      targetPort: 8899
    - name: tcp9999
      nodePort: 26874
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: workflow
    group: middleware
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  workflow-api.yaml: |
    Name: workflow
    Host: 0.0.0.0
    Port: 8899
    Timeout: 50000
    Log:
       Level: debug
       Mode: file
       Encoding: plain
       Path: /app/logs
    MySqlUrn: root:Root@123@tcp(10.99.43.9:3306)/workflow?charset=utf8mb4&parseTime=True&loc=Local
kind: ConfigMap
metadata:
  name: workflow-api.yaml
  namespace: uat-43
  resourceVersion: '408925842'