// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"github.com/zeromicro/go-zero/rest"

	api "workflow/internal/handler/api"
	canvas "workflow/internal/handler/canvas"
	datasource "workflow/internal/handler/datasource"
	model "workflow/internal/handler/model"
	user "workflow/internal/handler/user"
	workspace "workflow/internal/handler/workspace"
	"workflow/internal/svc"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// API发布列表
				Method:  http.MethodPost,
				Path:    "/api/list",
				Handler: api.ApiListHandler(serverCtx),
			},
			{
				// APIOnOff
				Method:  http.MethodPost,
				Path:    "/api/onoff",
				Handler: api.ApiOnOffHandler(serverCtx),
			},
			{
				// API发布
				Method:  http.MethodPost,
				Path:    "/api/publish",
				Handler: api.ApiPublishHandler(serverCtx),
			},
			{
				// API调用记录
				Method:  http.MethodPost,
				Path:    "/api/records",
				Handler: api.ApiRecordsHandler(serverCtx),
			},
			{
				// 创建API密钥
				Method:  http.MethodPost,
				Path:    "/api/secretkey/create",
				Handler: api.ApisecretKeyCreateHandler(serverCtx),
			},
			{
				// 删除API密钥
				Method:  http.MethodPost,
				Path:    "/api/secretkey/delete",
				Handler: api.ApisecretKeyDeleteHandler(serverCtx),
			},
			{
				// secretKeyList
				Method:  http.MethodPost,
				Path:    "/api/secretkey/list",
				Handler: api.ApiSecretKeyListHandler(serverCtx),
			},
			{
				// 修改API密钥到期时间
				Method:  http.MethodPost,
				Path:    "/api/secretkey/update/expirationtime",
				Handler: api.ApisecretKeyUpdateExpirationTimeHandler(serverCtx),
			},
			{
				// 修改API密钥状态
				Method:  http.MethodPost,
				Path:    "/api/secretkey/update/status",
				Handler: api.ApisecretKeyUpdateStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/workflow"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 画布详情
				Method:  http.MethodPost,
				Path:    "/canvas/detail",
				Handler: canvas.CanvasDetailHandler(serverCtx),
			},
			{
				// 画布更新
				Method:  http.MethodPost,
				Path:    "/canvas/draft",
				Handler: canvas.CanvasDraftHandler(serverCtx),
			},
			{
				// 全部运行
				Method:  http.MethodPost,
				Path:    "/canvas/run",
				Handler: canvas.CanvasRunHandler(serverCtx),
			},
			{
				// 获取画布运行详情
				Method:  http.MethodGet,
				Path:    "/canvas/run/detail/:recordId",
				Handler: canvas.GetCanvasRunDetailHandler(serverCtx),
			},
			{
				// 获取画布运行历史
				Method:  http.MethodGet,
				Path:    "/canvas/run/history/:workSpaceId",
				Handler: canvas.GetCanvasRunHistoryHandler(serverCtx),
			},
			{
				// 单组件运行
				Method:  http.MethodPost,
				Path:    "/canvas/run/single",
				Handler: canvas.CanvasRunSingleHandler(serverCtx),
			},
			{
				// 组件运行详情
				Method:  http.MethodPost,
				Path:    "/canvas/run/single/detail",
				Handler: canvas.CanvasRunSingleDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/canvas/run/history/:workSpaceId",
				Handler: canvas.GetCanvasRunHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/canvas/run/detail/:recordId",
				Handler: canvas.GetCanvasRunDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/workflow"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/publish",
				Handler: api.ApiPublishHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/list",
				Handler: api.ApiListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/onoff",
				Handler: api.ApiOnOffHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/records",
				Handler: api.ApiRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/secretkey/list",
				Handler: api.ApiSecretKeyListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/secretkey/create",
				Handler: api.ApisecretKeyCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/secretkey/update/status",
				Handler: api.ApisecretKeyUpdateStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/secretkey/update/expirationtime",
				Handler: api.ApisecretKeyUpdateExpirationTimeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/secretkey/delete",
				Handler: api.ApisecretKeyDeleteHandler(serverCtx),
			},
		},
		rest.WithPrefix("/workflow"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/module/new",
				Handler: model.ModuleNewHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/module/edit",
				Handler: model.ModuleEditHandler(serverCtx),
			},
		},
		rest.WithPrefix("/workflow"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/datasource/list",
				Handler: datasource.DatasourceListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/datasource/add",
				Handler: datasource.DatasourceAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/datasource/edit",
				Handler: datasource.DatasourceEditHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/datasource/delete",
				Handler: datasource.DatasourceDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/datasource/test",
				Handler: datasource.DatasourceTestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/workflow"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/logout",
				Handler: user.UserLogoutHandler(serverCtx),
			},
		},
		rest.WithPrefix("/workflow"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/info",
				Handler: user.UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/workflow"),
	)
}
