// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	canvasFieldNames          = builder.RawFieldNames(&Canvas{})
	canvasRows                = strings.Join(canvasFieldNames, ",")
	canvasRowsExpectAutoSet   = strings.Join(stringx.Remove(canvasFieldNames, "`id`"), ",")
	canvasRowsWithPlaceHolder = strings.Join(stringx.Remove(canvasFieldNames, "`id`"), "=?,") + "=?"
)

type (
	canvasModel interface {
		Insert(ctx context.Context, data *Canvas) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Canvas, error)
		FindOneByWorkspaceId(ctx context.Context, workspaceId string) (*Canvas, error)
		Update(ctx context.Context, data *Canvas) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCanvasModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Canvas struct {
		Id          int64     `db:"id"`
		WorkspaceId string    `db:"workspace_id"`
		Draft       string    `db:"draft"`
		CreateAt    time.Time `db:"create_at"`
		UpdateAt    time.Time `db:"update_at"`
		CreateBy    string    `db:"create_by"`
		UpdateBy    string    `db:"update_by"`
	}
)

func newCanvasModel(conn sqlx.SqlConn) *defaultCanvasModel {
	return &defaultCanvasModel{
		conn:  conn,
		table: "`canvas`",
	}
}

func (m *defaultCanvasModel) withSession(session sqlx.Session) *defaultCanvasModel {
	return &defaultCanvasModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`canvas`",
	}
}

func (m *defaultCanvasModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCanvasModel) FindOne(ctx context.Context, id int64) (*Canvas, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", canvasRows, m.table)
	var resp Canvas
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCanvasModel) FindOneByWorkspaceId(ctx context.Context, workspaceId string) (*Canvas, error) {
	var resp Canvas
	query := fmt.Sprintf("select %s from %s where `workspace_id` = ? limit 1", canvasRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, workspaceId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCanvasModel) Insert(ctx context.Context, data *Canvas) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, canvasRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.WorkspaceId, data.Draft, data.CreateAt, data.UpdateAt, data.CreateBy, data.UpdateBy)
	return ret, err
}

func (m *defaultCanvasModel) Update(ctx context.Context, newData *Canvas) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, canvasRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.WorkspaceId, newData.Draft, newData.CreateAt, newData.UpdateAt, newData.CreateBy, newData.UpdateBy, newData.Id)
	return err
}

func (m *defaultCanvasModel) tableName() string {
	return m.table
}
