// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	caseFieldNames          = builder.RawFieldNames(&Case{})
	caseRows                = strings.Join(caseFieldNames, ",")
	caseRowsExpectAutoSet   = strings.Join(stringx.Remove(caseFieldNames), ",")
	caseRowsWithPlaceHolder = strings.Join(stringx.Remove(caseFieldNames, "`id`"), "=?,") + "=?"
)

type (
	caseModel interface {
		Insert(ctx context.Context, data *Case) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Case, error)
		FindOneByUid(ctx context.Context, uid string) (*Case, error)
		Update(ctx context.Context, data *Case) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCaseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Case struct {
		Id          int64     `db:"id"`
		Uid         string    `db:"uid"`
		WorkspaceId string    `db:"workspace_id"`
		Name        string    `db:"name"`
		Params      string    `db:"params"`
		CreateAt    time.Time `db:"create_at"`
		UpdateAt    time.Time `db:"update_at"`
		CreateBy    string    `db:"create_by"`
		UpdateBy    string    `db:"update_by"`
	}
)

func newCaseModel(conn sqlx.SqlConn) *defaultCaseModel {
	return &defaultCaseModel{
		conn:  conn,
		table: "`case`",
	}
}

func (m *defaultCaseModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCaseModel) FindOne(ctx context.Context, id int64) (*Case, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", caseRows, m.table)
	var resp Case
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCaseModel) FindOneByUid(ctx context.Context, uid string) (*Case, error) {
	var resp Case
	query := fmt.Sprintf("select %s from %s where `uid` = ? limit 1", caseRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, uid)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCaseModel) Insert(ctx context.Context, data *Case) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, caseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Uid, data.WorkspaceId, data.Name, data.Params, data.CreateAt, data.UpdateAt, data.CreateBy, data.UpdateBy)
	return ret, err
}

func (m *defaultCaseModel) Update(ctx context.Context, newData *Case) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, caseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Uid, newData.WorkspaceId, newData.Name, newData.Params, newData.CreateAt, newData.UpdateAt, newData.CreateBy, newData.UpdateBy, newData.Id)
	return err
}

func (m *defaultCaseModel) tableName() string {
	return m.table
}
