// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rolesFieldNames          = builder.RawFieldNames(&Roles{})
	rolesRows                = strings.Join(rolesFieldNames, ",")
	rolesRowsExpectAutoSet   = strings.Join(stringx.Remove(rolesFieldNames, "`id`"), ",")
	rolesRowsWithPlaceHolder = strings.Join(stringx.Remove(rolesFieldNames, "`id`"), "=?,") + "=?"
)

type (
	rolesModel interface {
		Insert(ctx context.Context, data *Roles) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Roles, error)
		FindOneByCode(ctx context.Context, code string) (*Roles, error)
		Update(ctx context.Context, data *Roles) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRolesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Roles struct {
		Id          int64          `db:"id"`
		Name        string         `db:"name"`        // 角色名称
		Code        string         `db:"code"`        // 角色编码
		Description sql.NullString `db:"description"` // 角色描述
		Status      int64          `db:"status"`      // 状态 1:启用 0:禁用
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newRolesModel(conn sqlx.SqlConn) *defaultRolesModel {
	return &defaultRolesModel{
		conn:  conn,
		table: "`roles`",
	}
}

func (m *defaultRolesModel) withSession(session sqlx.Session) *defaultRolesModel {
	return &defaultRolesModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`roles`",
	}
}

func (m *defaultRolesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRolesModel) FindOne(ctx context.Context, id int64) (*Roles, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rolesRows, m.table)
	var resp Roles
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolesModel) FindOneByCode(ctx context.Context, code string) (*Roles, error) {
	var resp Roles
	query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", rolesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolesModel) Insert(ctx context.Context, data *Roles) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, rolesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.Description, data.Status, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultRolesModel) Update(ctx context.Context, newData *Roles) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, rolesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Code, newData.Description, newData.Status, newData.CreatedAt, newData.UpdatedAt, newData.Id)
	return err
}

func (m *defaultRolesModel) tableName() string {
	return m.table
}
