// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workspaceTagMappingFieldNames          = builder.RawFieldNames(&WorkspaceTagMapping{})
	workspaceTagMappingRows                = strings.Join(workspaceTagMappingFieldNames, ",")
	workspaceTagMappingRowsExpectAutoSet   = strings.Join(stringx.Remove(workspaceTagMappingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workspaceTagMappingRowsWithPlaceHolder = strings.Join(stringx.Remove(workspaceTagMappingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	workspaceTagMappingModel interface {
		Insert(ctx context.Context, data *WorkspaceTagMapping) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WorkspaceTagMapping, error)
		Update(ctx context.Context, data *WorkspaceTagMapping) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWorkspaceTagMappingModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WorkspaceTagMapping struct {
		Id          int64  `db:"id"`           // 主建
		TagId       int64  `db:"tag_id"`       // 标签ID
		WorkspaceId string `db:"workspace_id"` // 画布空间ID
	}
)

func newWorkspaceTagMappingModel(conn sqlx.SqlConn) *defaultWorkspaceTagMappingModel {
	return &defaultWorkspaceTagMappingModel{
		conn:  conn,
		table: "`workspace_tag_mapping`",
	}
}

func (m *defaultWorkspaceTagMappingModel) withSession(session sqlx.Session) *defaultWorkspaceTagMappingModel {
	return &defaultWorkspaceTagMappingModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`workspace_tag_mapping`",
	}
}

func (m *defaultWorkspaceTagMappingModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWorkspaceTagMappingModel) FindOne(ctx context.Context, id int64) (*WorkspaceTagMapping, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workspaceTagMappingRows, m.table)
	var resp WorkspaceTagMapping
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkspaceTagMappingModel) Insert(ctx context.Context, data *WorkspaceTagMapping) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, workspaceTagMappingRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TagId, data.WorkspaceId)
	return ret, err
}

func (m *defaultWorkspaceTagMappingModel) Update(ctx context.Context, data *WorkspaceTagMapping) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workspaceTagMappingRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TagId, data.WorkspaceId, data.Id)
	return err
}

func (m *defaultWorkspaceTagMappingModel) tableName() string {
	return m.table
}
