### 安装Httpx Requests插件
### 上传
POST http://127.0.0.1:8899/auto/upload
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="数产数据录入模版.xlsx""

< "/Users/qiangyuecheng/Downloads/数产数据录入模版.xlsx"
--WebAppBoundary--

### API
POST http://127.0.0.1:8899/workflow/mock
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "name": "xue",
  "age": 10
}

### API发布
POST http://127.0.0.1:8899/workflow/api/publish
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "id": "cs8vfql3sjtkvhkubulg",
  "apiName": "测试API",
  "apiDesc": "这是一个测试API"
}

### API发布列表
POST http://127.0.0.1:8899/workflow/api/list
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "current": 1,
  "pageSize": 10
}

### API上下线
POST http://127.0.0.1:8899/workflow/api/onoff
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "apiId": "asdasdasd",
  "status": "ON"
}

### API调用记录
POST http://127.0.0.1:8899/workflow/api/records
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "current": 1,
  "pageSize": 10,
  "apiId": "ctdder53sjtn9c6t20j0"
}

### API调用-单结构
POST http://198.19.249.3:9999/api/role/v1/ctdpe7l3sjtsoutieu20
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json
Authorization: Bearer 1ea00ca19d4f47b48c9ed8aec131674d

{
  "name": "张",
  "age": 11
}

### API调用-数组
POST http://127.0.0.1:9999/api/role/v1/ctdpe7l3sjtsoutieu20
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json
Authorization: Bearer 1ea00ca19d4f47b48c9ed8aec131674d

{
  "slice": [
    {
      "name": "张",
      "age": 10
    },
    {
      "name": "李四", 
      "age": 10
    }
  ]
}

### 创建API密钥
POST http://127.0.0.1:8899/workflow/api/secretykey/create
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "apiId": "ctdpe7l3sjtsoutieu20",
  "name": "测试密钥",
  "expirationTime": 1752410828282
} 

### API密钥列表
POST http://127.0.0.1:8899/workflow/api/secretykey/list
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "apiId": "asdasdasd",
  "current": 2,
  "pageSize": 4
}

### 修改API密钥状态
POST http://127.0.0.1:8899/workflow/api/secretykey/update/status
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "secretKey": "cf34266901974f67bae4f0f3510271c8",
  "status": "ON"
} 

### 修改API密钥到期时间
POST http://127.0.0.1:8899/workflow/api/secretykey/update/expirationtime
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "secretKey": "aacb67e882034f03bb5cd8da2afb1487",
  "expirationTime": 1752410828282
} 

### 删除API密钥
POST http://127.0.0.1:8899/workflow/api/secretykey/delete
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "secretKey": "aacb67e882034f03bb5cd8da2afb1487"
} 