### 查询画布运行记录
POST http://127.0.0.1:8888/workflow/trace/canvas/query
Content-Type: application/json

{
	"id": "d03l4kl3sjtgm7gc9su1",
	"current": 1,
	"pageSize": 10
}

### 查询组件运行结果
POST http://127.0.0.1:8888/workflow/trace/components/query
Content-Type: application/json

{
	"id": "d03l4kl3sjtgm7gc9su0",
  	"serialId": "trace-f605375862a6ea83ce1e05ec95a3679c"
}

### 查询组件运行结果
POST http://10.99.100.49:8888/workflow/trace/components/query
Content-Type: application/json

{
	"id": "d03l4kl3sjtgm7gc9su0",
  	"serialId": "trace-f605375862a6ea83ce1e05ec95a3679c"
}

### 查询goroutines运行数量
GET http://127.0.0.1:8888/workflow/stat/goroutines
