### 安装Httpx Requests插件
### 上传
POST http://127.0.0.1:8888/auto/upload
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="数产数据录入模版.xlsx""

< "/Users/qiangyuecheng/Downloads/数产数据录入模版.xlsx"
--WebAppBoundary--

### 设置key
POST http://127.0.0.1:8888/common/set/kv
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "key": "qqq",
  "value": "vvv",
  "spiderName": "ccc"
}

### 设置key生产
POST http://10.99.43.88:8888/common/set/kv
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "key": "qqq",
  "value": "vvv",
  "spiderName": "ccc"
}

### 创建 workspace
POST http://127.0.0.1:8888/workspace/new
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "workSpaceName": "工作空间名称",
  "workSpaceDesc": "工作空间描述",
  "workSpaceType": "workflow",
  "workSpaceTag": [
    "API","测试环境"
  ],
  "workSpaceIcon": "http://icon.com"
}


### 编辑 workspace name
POST http://127.0.0.1:8888/workspace/edit
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "id": "111222333",
  "workSpaceName": "namename"
}

### 列表 workspace
POST http://127.0.0.1:8888/workspace/list
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "workSpaceTag": [
    1
  ],
  "current": 1,
  "pageSize": 2
}

### 列表-带条件 workspace
POST http://127.0.0.1:8888/workspace/list
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "workSpaceName": "demoString",
  "workSpaceType": "demoString",
  "workSpaceTag": [
    "demoString"
  ],
  "current": 0,
  "pageSize": 0
}