### 安装Httpx Requests插件
### 上传
POST http://127.0.0.1:8888/auto/upload
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="数产数据录入模版.xlsx""

< "/Users/qiangyuecheng/Downloads/数产数据录入模版.xlsx"
--WebAppBoundary--

### 设置key
POST http://127.0.0.1:8888/common/set/kv
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "key": "qqq",
  "value": "vvv",
  "spiderName": "ccc"
}

### 设置key生产
POST http://10.99.43.88:8888/common/set/kv
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "key": "qqq",
  "value": "vvv",
  "spiderName": "ccc"
}

### 获取key
POST http://127.0.0.1:8888/common/get/vByk
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "key": "qqq11"
}

