### 画布-详情
POST http://127.0.0.1:8899/workflow/canvas/detail
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "workSpaceId": "crvpmf53sjtsppvoiogg"
}

### 画布-执行-全部
POST http://127.0.0.1:8899/workflow/canvas/run
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "id": "ctcnvjl3sjtg1ku5p220"
}

### 画布-执行-单组件
POST http://127.0.0.1:8899/workflow/canvas/run/single
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "id": "ctcnvjl3sjtg1ku5p220",
  "nodeId": "ctcnvjl3sjtg1ku5p220"
}


### 画布-更新
POST http://127.0.0.1:8899/workflow/canvas/draft
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "workSpaceId": "crvpmf53sjtsppvoiogg"
}

### 画布-执行记录
GET http://127.0.0.1:8899/workflow/canvas/run/history/asdasd
User-Agent: Apifox/1.0.0 (https://apifox.com)

### 画布-执行记录详情
GET http://127.0.0.1:8899/workflow/canvas/run/detail/22222
User-Agent: Apifox/1.0.0 (https://apifox.com)

### API-发布
POST http://127.0.0.1:8899/workflow/canvas/publish
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json

{
  "id": "cs8vfql3sjtkvhkubulg",
  "apiName": "雪兔测试并行1",
  "apiDesc": "嘻嘻嘻 哈哈哈"
}